# Generated by Django 6.0.2 on 2026-03-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("count_tickets", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_place", models.CharField(max_length=200)),
                ("to_place", models.CharField(max_length=200)),
                ("day", models.CharField(max_length=50)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "train_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railway.train"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wagon_num", models.IntegerField(verbose_name="wagon")),
                ("seat_num", models.IntegerField(verbose_name="seat")),
                ("taken", models.BooleanField(default=False)),
                (
                    "train_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railway.train"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travel_date", models.DateField(null=True)),
                ("qr_code", models.CharField(blank=True, max_length=20, unique=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "seat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railway.seat"
                    ),
                ),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="railway.station",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railway.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_num", models.CharField(max_length=100)),
                ("cvv", models.IntegerField()),
                ("date", models.CharField(max_length=10)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railway.user"
                    ),
                ),
            ],
        ),
    ]
